config/routes.rb
Rails.application.routes.draw do
  resources :enigmas
  resources :extra_pages
  post 'enigmas/:id', controller: 'enigmas', action: 'check', as: 'check'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "welcome#show"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/enigma.rb
class Enigma < ApplicationRecord
  has_many :extra_pages
end

app/models/extra_page.rb
class ExtraPage < ApplicationRecord
  belongs_to :enigma
end

app/models/user.rb
class User < ApplicationRecord
  include Clearance::User
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
end

app/controllers/enigmas_controller.rb
class EnigmasController < ApplicationController
  before_action :set_enigma, only: [:show, :edit, :update, :destroy]

  # GET /enigmas
  # GET /enigmas.json
  def index
    @enigmas = Enigma.all
    @extra_pages = ExtraPage.all
  end

  def check
    user_answer = params[:user_answer];
    enigma_answer = params[:enigma_answer];
    id = params[:id];
    all_enigmas = Enigma.all;
    last_enigma_id = all_enigmas.last.id.to_s;
    if user_answer == enigma_answer
      if last_enigma_id.to_i < id.to_i+1
        User.find_by_email(current_user.email).update(level: 0);
        next_number = 0
        next_page = "/enigmas/"+next_number.to_s;
        redirect_to next_page;
        # puts "\n\n\n\n\n\n\n\n VOCE VENCEU !!! \n\n\n\n\n\n\n"
      else
        User.find_by_email(current_user.email).update(level: id.to_i+1);
        # puts "\n\n\n\n\n\n\n\n " + User.find_by_email(current_user.email).level.to_s + " \n\n\n\n\n\n\n"
        next_number = id.to_i+1
        next_page = "/enigmas/"+next_number.to_s;
        redirect_to next_page;
      end
      # "window.location.href='/enigmas/<%= current_user.level %>'"
      # puts "\n\n\n                " + user_answer + enigma_answer + id + " \n\n\n"
    else
      next_number = id.to_i;
      next_page = "/enigmas/"+next_number.to_s;
      redirect_to next_page;
    end
  end

  # GET /enigmas/1
  # GET /enigmas/1.json
  def show
    @extra_pages_enigma = @enigma.extra_pages
    if (current_user.email == "admin@admin.admin")
    elsif (current_user.level != params[:id].to_i)
      redirect_back fallback_location: "/cheater.html";
    end
  end

  # GET /enigmas/new
  def new
    @enigma = Enigma.new
  end

  # GET /enigmas/1/edit
  def edit
  end

  # POST /enigmas
  # POST /enigmas.json
  def create
    @enigma = Enigma.new(enigma_params)

    respond_to do |format|
      if @enigma.save
        format.html { redirect_to @enigma, notice: 'Enigma was successfully created.' }
        format.json { render :show, status: :created, location: @enigma }
      else
        format.html { render :new }
        format.json { render json: @enigma.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /enigmas/1
  # PATCH/PUT /enigmas/1.json
  def update
    respond_to do |format|
      if @enigma.update(enigma_params)
        format.html { redirect_to @enigma, notice: 'Enigma was successfully updated.' }
        format.json { render :show, status: :ok, location: @enigma }
      else
        format.html { render :edit }
        format.json { render json: @enigma.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /enigmas/1
  # DELETE /enigmas/1.json
  def destroy
    @enigma.destroy
    respond_to do |format|
      format.html { redirect_to enigmas_url, notice: 'Enigma was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_enigma
      @enigma = Enigma.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def enigma_params
      params.require(:enigma).permit(:image, :message, :answer)
    end
end

app/controllers/extra_pages_controller.rb
class ExtraPagesController < ApplicationController
  before_action :set_extra_page, only: [:show, :edit, :update, :destroy]

  # GET /extra_pages
  # GET /extra_pages.json
  def index
    @extra_pages = ExtraPage.all
  end

  # GET /extra_pages/1
  # GET /extra_pages/1.json
  def show
    extra_page_enigma_id = @extra_page.enigma.id
    if (current_user.email == "admin@admin.admin")
    elsif (current_user.level != extra_page_enigma_id.to_i)
      redirect_back fallback_location: "/cheater.html";
    end
  end

  # GET /extra_pages/new
  def new
    @extra_page = ExtraPage.new
  end

  # GET /extra_pages/1/edit
  def edit
  end

  # POST /extra_pages
  # POST /extra_pages.json
  def create
    @extra_page = ExtraPage.new(extra_page_params)

    respond_to do |format|
      if @extra_page.save
        format.html { redirect_to @extra_page, notice: 'Extra page was successfully created.' }
        format.json { render :show, status: :created, location: @extra_page }
      else
        format.html { render :new }
        format.json { render json: @extra_page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /extra_pages/1
  # PATCH/PUT /extra_pages/1.json
  def update
    respond_to do |format|
      if @extra_page.update(extra_page_params)
        format.html { redirect_to @extra_page, notice: 'Extra page was successfully updated.' }
        format.json { render :show, status: :ok, location: @extra_page }
      else
        format.html { render :edit }
        format.json { render json: @extra_page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /extra_pages/1
  # DELETE /extra_pages/1.json
  def destroy
    @extra_page.destroy
    respond_to do |format|
      format.html { redirect_to extra_pages_url, notice: 'Extra page was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_extra_page
      @extra_page = ExtraPage.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def extra_page_params
      params.require(:extra_page).permit(:text, :image, :enigma_id, :kind)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/enigmas_helper.rb
module EnigmasHelper
end

app/helpers/extra_pages_helper.rb
module ExtraPagesHelper
end

app/views/enigmas/_form.html.erb
<%= form_with(model: enigma, local: true) do |form| %>
  <% if enigma.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(enigma.errors.count, "error") %> prohibited this enigma from being saved:</h2>

      <ul>
      <% enigma.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="edit-enigma-input">
    <!-- <%= form.label :image %> -->
    <%= form.text_field :image, placeholder: "Enigma URL image" %>
  </div>

  <div class="edit-enigma-input">
    <!-- <%= form.label :message %> -->
    <%= form.text_field :message, placeholder: "Enigma message" %>
  </div>

  <div class="edit-enigma-input">
    <!-- <%= form.label :answer %> -->
    <%= form.text_field :answer, placeholder: "Enigma answer" %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/enigmas/edit.html.erb
<head>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.8/css/solid.css">
  <script src="https://use.fontawesome.com/releases/v5.0.7/js/all.js"></script>
</head>

<body>
  <% if current_user.email == "admin@admin.admin" %>
    <div class="modal-dialog text-center">
      <div class="col-sm-8 main-section">
        <div class="modal-content">
          <%= render 'form', enigma: @enigma %>
          <div><a style="color: #4272DB" href="/enigmas">Back</a>
        </div>
      </div>
    </div>
  </div>
  <% else %>
    <script language="JavaScript">
      window.location.href='/cheater.html';
    </script>
  <% end %>
</body>

app/views/enigmas/index.html.erb
  <head>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.8/css/solid.css">
  <script src="https://use.fontawesome.com/releases/v5.0.7/js/all.js"></script>
</head>

<body>
  <% if current_user.email == "admin@admin.admin" %>
    <div class="edit-enigmas">
      <div class="about"><font size="5">ENIGMAS</font></div>
      <table border="5" bgcolor="#3b4652">
        <thead>
          <tr>
            <th>ID</th>
            <th>Image</th>
            <th>Message</th>
            <th>Answer</th>
            <th colspan="2"><a style="color: #4272DB" href="/enigmas/new">New Enigma</a></th>
          </tr>
        </thead>

        <tbody>
          <% @enigmas.each do |enigma| %>
            <tr>
              <td><%= enigma.id %></td>
              <td>
                <% if enigma.image.size <= 40 %>
                  <%= enigma.image %>
                <% else %>
                  <%= "image is too big to put here" %>
                <% end %>
              </td>
              <td>
                <% if enigma.message.size <= 40 %>
                  <%= enigma.message %>
                <% else %>
                  <%= "message is too big to put here" %>
                <% end %>
              </td>
              <td>
                <% if enigma.answer.size <= 40 %>
                  <%= enigma.answer %>
                <% else %>
                  <%= "answer is too big to put here" %>
                <% end %>
              </td>
              <td><a style="color: #4272DB" <%= link_to 'Show', enigma %></td></a>
              <td><a style="color: #4272DB" <%= link_to 'Edit', edit_enigma_path(enigma) %></td></a>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  <% else %>
    <script language="JavaScript">
      window.location.href='/cheater.html';
    </script>
  <% end %>
  <div class="edit-extra-pages">
    <div class="about"><font size="5">EXTRA PAGES</font></div>
    <table border="5" bgcolor="#3b4652">
      <thead>
        <tr>
          <th>Kind</th>
          <th>Text</th>
          <th>Image</th>
          <th>Enigma ID</th>
          <th colspan="2"><a style="color: #4272DB" href="/extra_pages/new">New Extra Page</a></th>
        </tr>
      </thead>

      <tbody>
        <% last_enigma_id_aux = @enigmas.last.id %>
        <% counter = 0 %>
        <% while counter <= last_enigma_id_aux %>
          <% @extra_pages.each do |extra_page| %>
            <tr>
              <% if extra_page.enigma.id == counter %>
                <td><%= extra_page.kind %></td>
                <td>
                  <% if extra_page.text.size <= 50 %>
                    <%= extra_page.text %>
                  <% else %>
                    <%= "text is too big to put here" %>
                  <% end %>
                </td>
                <td>
                  <% if extra_page.image.size <= 50 %>
                    <%= extra_page.image %>
                  <% else %>
                    <%= "image is too big to put here" %>
                  <% end %>
                </td>
                <td><%= extra_page.enigma.id %></td>
                <td><a style="color: #4272DB" <%= link_to 'Show', extra_page %></td></a>
                <td><a style="color: #4272DB" <%= link_to 'Edit', edit_extra_page_path(extra_page) %></td></a>
              <% end %>
            </tr>
          <% end %>
          <% counter+=1 %>
        <% end %>
      </tbody>
    </table>
  </div>

  <br>

</body>

app/views/enigmas/new.html.erb
<head>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.8/css/solid.css">
  <script src="https://use.fontawesome.com/releases/v5.0.7/js/all.js"></script>
</head>

<body>
  <% if current_user.email == "admin@admin.admin" %>
    <div class="modal-dialog text-center">
      <div class="col-sm-8 main-section">
        <div class="modal-content">
          <%= render 'form', enigma: @enigma %>
          <div><a style="color: #4272DB" href="/enigmas">Back</a>
        </div>
      </div>
    </div>
  </div>
  <% else %>
    <script language="JavaScript">
      window.location.href='/cheater.html';
    </script>html">
  <% end %>
</body>

app/views/enigmas/show.html.erb
<head>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.8/css/solid.css">
  <script src="https://use.fontawesome.com/releases/v5.0.7/js/all.js"></script>
</head>

<body>
  <% if @extra_pages_enigma.count > 0 %>Extra links:<% end %>
  <% @extra_pages_enigma.each do |extra_page| %>
    <% if extra_page.kind == "hint" %><td><a style="color: #4272DB" <%= link_to extra_page.kind, extra_page, data: { confirm: 'Are you sure? Hints can make this game loses fun' } %></td></a>
    <% else %><td><a style="color: #4272DB" <%= link_to extra_page.kind, extra_page %></td></a><% end %>
    <% if extra_page != @extra_pages_enigma.last %><%= "," %><% end %>
  <% end %>
  <%= form_tag :action => 'show' do %>
    <input type="hidden" value="<%= @enigma %>" name="enigma" id="enigma_id">
  <% end %>
  <div class="text-center">
    <div class="enigma-image">
      <% if @enigma.image != "" %><img src="<%= @enigma.image %>" alt="Enigma">
      <% else %><br/><br/><br/><br/><br/><% end %>
    </div>
    <font size="5"><%= @enigma.message %></font>
    <%= form_tag :action => 'check' do %>
      <input type="hidden" value="<%= @enigma.answer %>" name="enigma_answer" id="enigma_id">
      <!-- text_field_tag 'user_answer' -->
      <div class="answer-field">
        <input placeholder="Enter you answer here and press enter" type="text" name="user_answer" id="user_answer">
      </div>
    <% end %>
  </div>
</body>


<!-- <p id="notice"><%= notice %></p>

<p>
  <strong>Image:</strong>
  <%= @enigma.image %>
</p>

<p>
  <strong>Message:</strong>
  <%= @enigma.message %>
</p>

<p>
  <strong>Answer:</strong>
  <%= @enigma.answer %>
</p>

<%= link_to 'Edit', edit_enigma_path(@enigma) %> |
<%= link_to 'Back', enigmas_path %> -->

app/views/extra_pages/_form.html.erb
<%= form_with(model: extra_page, local: true) do |form| %>
  <% if extra_page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(extra_page.errors.count, "error") %> prohibited this extra_page from being saved:</h2>

      <ul>
      <% extra_page.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="edit-enigma-input-select">
    Kind: <%= form.select :kind, ['normal', 'hint'] %>
  </div>

  <div class="edit-enigma-input">
    <%= form.text_field :text, placeholder:"text" %>
  </div>

  <div class="edit-enigma-input">
    <%= form.text_field :image, placeholder:"image URL" %>
  </div>

  <div class="edit-enigma-input-select">
    Enigma ID: <%= form.collection_select(:enigma_id, Enigma.all, :id, :id, prompt: false) %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/extra_pages/edit.html.erb
<head>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.8/css/solid.css">
  <script src="https://use.fontawesome.com/releases/v5.0.7/js/all.js"></script>
</head>

<body>
  <% if current_user.email == "admin@admin.admin" %>
    <div class="modal-dialog text-center">
      <div class="col-sm-8 main-section">
        <div class="modal-content">
          <%= render 'form', extra_page: @extra_page %>
          <div><a style="color: #4272DB" href="/enigmas">Back</a>
        </div>
      </div>
    </div>
  </div>
  <% else %>
    <script language="JavaScript">
      window.location.href='/cheater.html';
    </script>
  <% end %>
</body>

app/views/extra_pages/index.html.erb
<script language="JavaScript">
  window.location.href='/404.html';
</script>html">

app/views/extra_pages/new.html.erb
<head>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.8/css/solid.css">
  <script src="https://use.fontawesome.com/releases/v5.0.7/js/all.js"></script>
</head>

<body>
  <% if current_user.email == "admin@admin.admin" %>
    <div class="modal-dialog text-center">
      <div class="col-sm-8 main-section">
        <div class="modal-content">
          <%= render 'form', extra_page: @extra_page %>
          <div><a style="color: #4272DB" href="/enigmas">Back</a>
        </div>
      </div>
    </div>
  </div>
  <% else %>
    <script language="JavaScript">
      window.location.href='/cheater.html';
    </script>html">
  <% end %>
</body>

app/views/extra_pages/show.html.erb
<head>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.8/css/solid.css">
  <script src="https://use.fontawesome.com/releases/v5.0.7/js/all.js"></script>
</head>

<body>
  <%= form_tag :action => 'show' do %>
    <input type="hidden" value="<%= @extra_page %>" name="extra_page" id="extra_page_id">
  <% end %>
  <div class="extra-page-content">
        <div class="extra-page-text">
          <font size = "5">
            <% if @extra_page.image == "" %><br/><br/><br/><br/><br/><% end %>
            <%= @extra_page.text %>
          </font>
      </div>

      <div class="enigma-image">
        <% if @extra_page.image != "" %><img src="<%= @extra_page.image %>" alt="Enigma"><% end %>
      </div>
      <div class="extra-page-button"><button onclick="window.location.href='/enigmas/<%= current_user.level %>'">back</button></div >
  </div>
</body>

<!-- <p id="notice"><%= notice %></p>

<p>
  <strong>Text:</strong>
  <%= @extra_page.text %>
</p>

<p>
  <strong>Image:</strong>
  <%= @extra_page.image %>
</p>

<p>
  <strong>Enigma:</strong>
  <%= @extra_page.enigma.id %>
</p>

<%= link_to 'Edit', edit_extra_page_path(@extra_page) %> |
<%= link_to 'Back', extra_pages_path %> -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RiddleSite</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="new-navbar">
      <header>
        <% if signed_in? %>
          <%= button_to "Sign out", sign_out_path, method: :delete %>
          <div class="message-navbar">
            <% if current_user.email == "admin@admin.admin" %>
              You are on admin mode <a href="/enigmas" style="color: #4272DB">edit enigmas</a>
            <% else %>
              <%= current_user.email %>
            <% end %>
          </div>
        <% else %>
          <div class="navbar-sign-in">
            <button onclick="window.location.href='/sign_in'">Sign in</button>
            <font size = "1"> <%= "Your first enigma answer is in login page" %> </font>
          </div>
        <% end %>
        <div id="flash">
          <% flash.each do |key, value| %>
            <div class="flash <%= key %>"><%= value %></div>
          <% end %>
        </div>
      </header>
      <section>
        <div id="flash">
          <% flash.each do |key, value| %>
            <div class="flash <%= key %>"><%= value %></div>
          <% end %>
        </div>
        <%= yield %>
      </section>
    </div>
  </body>
</html>

app/views/users/_form.html.erb
<div class="text-field">
  <%= form.label :email %>
  <%= form.text_field :email, type: 'email' %>
</div>

<div class="password-field">
  <%= form.label :password %>
  <%= form.password_field :password %>
</div>

app/views/users/new.html.erb
<head>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.8/css/solid.css">
  <script src="https://use.fontawesome.com/releases/v5.0.7/js/all.js"></script>
</head>

<body>
  <%= form_for @user do |form| %>
    <div class="modal-dialog text-center">
      <div class="col-sm-8 main-section">
        <div class="modal-content">
          <form class="col-12">
            <div class "space">
               <p></p>
            </div>
            <div class="form-group">
              <input type="email" name="user[email]" id="session_email" placeholder="Enter Email">
            </div>

            <div class="password-field">
              <input type="password" name="user[password]" id="session_password" placeholder="Enter Password">
            </div>
            <div class="submit-field">
              <button type="submit" name="commit" value="Sign up" class="btn"><i class="fas fa-sign-in-alt"></i>Register</button>
            </div>
          </form>
          <div class="other-links">
              <div class="col-12 sign-up">
                <%= link_to t(".sign_in"), sign_in_path %>
              </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</body>

app/views/welcome/show.html.erb
<head>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.8/css/solid.css">
  <script src="https://use.fontawesome.com/releases/v5.0.7/js/all.js"></script>
</head>

<body>
    <div class="modal-dialog text-center">
      <img src="https://i.imgur.com/s34ESNe.png" alt="Logo">
    </div>
    <div class="message text-center">
      <div class="login-button">
        <% if signed_in? %>
          <button class="btn" onclick="window.location.href='/enigmas/<%= current_user.level %>'">Play</button>
        <% else %>
          <button class="btn" onclick="window.location.href='/sign_in'">Login</button>
        <% end %>
      </div>
      <div class "message text-center">
        <% if signed_in? %>
          <p><font size="5">Answers are always lowercase and without space</font></p>
        <% else %>
          <p><font size="5">You must login to play</font></p>
        <% end %>
      </div>
    </div>
</body>